[Update] rename package

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,7 +1,16 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
-echo '💬 Spell Checker,🎨 Styling,💄 Linting then 🚀 build the application'
+echo '🩺 Code Checking,💬 Spell Checker,🎨 Styling,💄 Linting then 🚀 build the application'
+
+# if test passes
+echo '✅ test passed'
+
+# Check Tsconfig standard
+npm run check:types || (
+  echo '🚨 Check Types failed'
+  false
+)
 
 # if Check types passes
 echo '✅ Check types passed'
@@ -35,3 +44,14 @@ echo '✅ Lint passed'
 
 # if everything is passes... try to run build
 echo '💚 Alright... Code looks good to me and tests passed.... now trying to build'
+
+# Build
+npm run build || (
+  echo '🚨 Build failed'
+  false
+)
+
+# if Build passes
+echo '✅ Builded Successfully'
+
+git add .
