[fix] eslint config

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,7 +1,7 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
-echo '💬 Spell Checker,🎨 Styling then 🚀 build the application'
+echo '💬 Spell Checker,🎨 Styling,💄 Linting then 🚀 build the application'
 
 # if Check types passes
 echo '✅ Check types passed'
@@ -23,6 +23,15 @@ npm run check:format || (
 
 # if Prettier passes
 echo '✅ prettier passed'
+
+# Check Linting
+npm run check:lint || (
+  echo '🚨 Check Linting failed'
+  false
+)
+
+# if Linting passes
+echo '✅ Lint passed'
 
 # if everything is passes... try to run build
 echo '💚 Alright... Code looks good to me and tests passed.... now trying to build'
