refactor(core): :recycle: refactor project using `npx @js-omar/create-ts-app` version `3.0.19`

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,7 +1,4 @@
-#!/bin/sh
-. "$(dirname "$0")/_/husky.sh"
+#!/usr/bin/env sh
+. "$(dirname -- "$0")/_/husky.sh"
 
-npm run test:all || (
-  echo '🚨 Test Failed'
-  false
-)
+npm run test:all:ci || (echo '🚨 Test Failed'; false)
