feat: :sparkles: add `lint-stage` package to ci/cd

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,7 +1,7 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-npm run test || (
-  echo '🚨 Test Failed'
+npx lint-staged || (
+  echo '🚨 Lint Failed'
   false
 )
